name: BuildModule

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Checkout project
      uses: actions/checkout@v2

    - name: Fetch tags for GitVersion
      run: git fetch --prune

    - name: Run GitVersion
      # You may pin to the exact commit or the version.
      # uses: roryprimrose/rungitversion@80f02b02c55975abac3836750542fe3d596c2cf4
      uses: roryprimrose/rungitversion@v1.0.0
      with:
        # "true" to use GitVersion /nofetch, any other value to enable fetch
        nofetch: false # default is false
        # "true" to use GitVersion /nocache, any other value to enable cache
        nocache: false # default is false

    # - name: Install GitVersion
    #   uses: gittools/actions/gitversion/setup@v0.9
    #   with:
    #     versionSpec: '5.6.x'

    # - name: Use GitVersion
    #   id: gitversion
    #   uses: gittools/actions/gitversion/execute@v0.9

    - name: Setup cache for build dependencies
      id: cacheBuildDependencies
      uses: actions/cache@v2
      with:
        path: tmp/Modules
        key: ${{ hashFiles('Scripts/DownloadBuildDependencies.ps1') }}

    - name: Download required build dependencies
      if: steps.cacheBuildDependencies.outputs.cache-hit != 'true'
      shell: pwsh
      run: ./Scripts/DownloadBuildDependencies.ps1

    - name: Build Module
      run: |
        $ModulePath = Resolve-Path -Path tmp/Modules | Select-Object -ExpandProperty Path
        $Env:PSModulePath = $ModulePath, $Env:PSModulePath -join [System.IO.Path]::PathSeparator
        Import-Module ModuleBuilder
        Build-Module -SourcePath .\Source -SemVer ${{ steps.gitversion.outputs.SemVer }}
      shell: pwsh

    - name: Upload built module
      uses: actions/upload-artifact@v2
      with: 
        name: MyTesla
        path: bin/MyTesla