name: BuildModule

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Checkout project
      uses: actions/checkout@v2

    - name: Fetch tags for GitVersion
      run: git fetch --tags

    - name: Fetch main for GitVersion
      if: github.ref != 'refs/heads/main'
      run: git branch --create-reflog main origin/main

    - name: GitVersion
      id: gitversion  # step id used as reference for output values
      uses: roryprimrose/rungitversion@v1.0.0

    - name: Setup cache for build dependencies
      id: cacheBuildDependencies
      uses: actions/cache@v2
      with:
        path: tmp/Modules
        key: ${{ hashFiles('Scripts/DownloadBuildDependencies.ps1') }}

    - name: Download required build dependencies
      if: steps.cacheBuildDependencies.outputs.cache-hit != 'true'
      shell: pwsh
      run: ./Scripts/DownloadBuildDependencies.ps1

    - name: Build Module
      run: |
        $ModulePath = Resolve-Path -Path tmp/Modules | Select-Object -ExpandProperty Path
        $Env:PSModulePath = $ModulePath, $Env:PSModulePath -join [System.IO.Path]::PathSeparator
        Import-Module ModuleBuilder
        Build-Module -SourcePath .\Source -SemVer ${{ steps.gitversion.outputs.SemVer }}
      shell: pwsh

    - name: Upload built module
      uses: actions/upload-artifact@v2
      with: 
        name: MyTesla
        path: bin/MyTesla